# Generated by Django 5.0.4 on 2026-03-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0002_alter_barbershop_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='has_shop_admin',
            field=models.BooleanField(default=False, verbose_name='Есть администратор барбершопа'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='shop_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_barbershop', to=settings.AUTH_USER_MODEL, verbose_name='Администратор барбершопа'),
        ),
    ]
